# Generated by Django 3.1.7 on 2021-03-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableFactory', '0002_auto_20210324_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='feet_id',
            new_name='feet',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='leg_id',
            new_name='leg',
        ),
    ]
