# Generated by Django 3.1.7 on 2021-03-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableFactory', '0004_auto_20210324_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feet',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feet',
            name='radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feet',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
